name: Code quality

on: pull_request

jobs:
  job:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.8

    - uses: actions/cache@v2.1.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-tests.txt') }}
        restore-keys: ${{ runner.os }}-pip-${{ hashFiles('requirements-tests') }}

    - name: Install requirements
      run: python -m pip install -r requirements-tests.txt

    - name: Style
      run: python -m black --check --diff scripts tests

    - name: Lint
      run: python -m flake8 scripts tests

    - name: Types
      run: python -m mypy scripts
